version: 2.1

orbs:
  newspack: newspack/newspack@1.4.4

workflows:
  version: 2
  all:
    jobs:
      - newspack/build
      - newspack/lint-js-scss:
          requires:
            - newspack/build
      - newspack/test-js:
          requires:
            - newspack/build
      - newspack/check-typescript:
          requires:
            - newspack/build
      - newspack/build-distributable:
          requires:
            - newspack/build
          archive-name: 'newspack-plugin'
          filters:
            branches:
              only:
                - trunk
      - newspack/release:
          requires:
            - newspack/build
          filters:
            branches:
              only:
                - release
                - alpha
                - /^hotfix\/.*/
                - /^epic\/.*/
      - newspack/post-release:
          requires:
            - newspack/release
          filters:
            branches:
              only:
                - release
  php:
    jobs:
      - newspack/lint-php
      - newspack/test-php
